import {createId,summary,validMeasurement} from './core.js';
import {loadState,saveState} from './storage.js';
const $=s=>document.querySelector(s); let {state,error:loadError}=loadState(), pending=null, toastTimer,focusBack;
const els={wallForm:$('#wall-form'),openingForm:$('#opening-form'),wallList:$('#wall-list'),openingList:$('#opening-list'),wallCount:$('#wall-count'),area:$('#area-result'),exact:$('#exact-result'),buy:$('#buy-result'),coats:$('#coat-count'),toast:$('#toast'),dialog:$('#confirm-dialog'),dialogTitle:$('#dialog-title'),dialogMessage:$('#dialog-message'),clearOpenings:$('#clear-openings'),resetPlan:$('#reset-plan'),liveNote:$('#live-note'),openingSummary:$('#opening-summary')};
const fmt=n=>Math.round(n*10)/10;
function notify(message,persistent=false){els.toast.textContent=message;els.toast.classList.add('show');clearTimeout(toastTimer);if(!persistent)toastTimer=setTimeout(()=>els.toast.classList.remove('show'),4500);}
function persist(){const error=saveState(state);if(error)notify(error,true);return error;}
function itemHTML(item,kind){const name=item.type??'Wall', area=fmt(item.width*item.height);return `<li><span><b>${name}</b><small>${item.width} ft x ${item.height} ft · ${area} sq ft</small></span><button class="remove" type="button" data-kind="${kind}" data-id="${item.id}" aria-label="Remove ${name}">×</button></li>`;}
const draft=(kind,form,base=state)=>{const d=new FormData(form),w=+d.get('width'),h=+d.get('height');return validMeasurement(w,h)&&(kind!='walls'||base.walls.length<6)?{...base,[kind]:[...base[kind],{width:w,height:h}]}:base};
function render(){els.wallCount.textContent=`${state.walls.length} of 6`;els.wallList.innerHTML=state.walls.length?state.walls.map(x=>itemHTML(x,'walls')).join(''):'<li class="empty">No walls yet.</li>';els.openingList.innerHTML=state.openings.length?state.openings.map(x=>itemHTML(x,'openings')).join(''):'<li class="empty">No openings saved.</li>';els.coats.value=state.coats;const base=summary(state),s=summary(draft('openings',els.openingForm,draft('walls',els.wallForm))),preview=s.paintable-base.paintable,openingArea=state.openings.reduce((n,x)=>n+x.width*x.height,0);els.area.textContent=fmt(s.paintable);els.exact.textContent=s.exact.toFixed(2);els.buy.textContent=s.buy;els.liveNote.textContent=preview?`${preview>0?'+':''}${fmt(preview)} sq ft preview while typing.`:'';els.openingSummary.textContent=state.openings.length?`${state.openings.length} opening${state.openings.length===1?'':'s'} subtract ${fmt(openingArea)} sq ft before coats.`:'';$('#clear-walls').disabled=!state.walls.length;els.clearOpenings.disabled=!state.openings.length;els.resetPlan.disabled=!state.walls.length&&!state.openings.length&&state.coats===2;}
function addMeasurement(form,kind){const data=new FormData(form),width=+data.get('width'),height=+data.get('height');const error=$(kind==='walls'?'#wall-error':'#opening-error');if(!validMeasurement(width,height)){error.textContent='Use values from 0.1 to 10,000.';form.querySelectorAll('input').forEach(x=>x.setAttribute('aria-invalid','true'));return;}if(kind==='walls'&&state.walls.length>=6){error.textContent='Six walls maximum.';return;}error.textContent='';form.querySelectorAll('input').forEach(x=>x.removeAttribute('aria-invalid'));state[kind].push({id:createId(),width,height,...(kind==='openings'?{type:String(data.get('type'))}: {})});form.reset();const saved=!persist();render();if(saved)notify(kind==='walls'?'Wall added.':`${data.get('type')} subtracted.`);}
els.wallForm.addEventListener('submit',e=>{e.preventDefault();addMeasurement(e.currentTarget,'walls')});els.openingForm.addEventListener('submit',e=>{e.preventDefault();addMeasurement(e.currentTarget,'openings')});
document.addEventListener('input',e=>{if(e.target.form?.classList.contains('entry'))render()});
function confirm(action,message,trigger){pending=action;focusBack=trigger;els.dialogTitle.textContent=action.reset?'Reset this plan?':'Remove this item?';els.dialogMessage.textContent=message;els.dialog.querySelector('[value=confirm]').textContent=action.reset?'Reset':'Remove';els.dialog.showModal();}
document.addEventListener('click',e=>{const button=e.target.closest('[data-kind]');if(button){const entry=state[button.dataset.kind].find(x=>x.id===button.dataset.id);confirm({kind:button.dataset.kind,id:button.dataset.id},`Remove this ${entry?.type??'wall'} from your plan?`,button);}if(e.target.id==='clear-walls'&&state.walls.length)confirm({kind:'walls',all:true},`Remove all ${state.walls.length} wall${state.walls.length===1?'':'s'}?`,e.target);if(e.target.id==='clear-openings'&&state.openings.length)confirm({kind:'openings',all:true},`Remove all ${state.openings.length} opening${state.openings.length===1?'':'s'}?`,e.target);if(e.target.id==='reset-plan'&&!e.target.disabled)confirm({reset:true},'Remove all walls and openings, then return coats to two?',e.target);const change=e.target.dataset.coatChange;if(change){state.coats=Math.max(1,Math.min(10,state.coats+Number(change)));persist();render();}});
els.dialog.addEventListener('close',()=>{if(els.dialog.returnValue==='confirm'&&pending){const label=pending.reset?'Plan reset.':pending.all?'Items removed.':'Item removed.';state=pending.reset?{walls:[],openings:[],coats:2}:{...state,[pending.kind]:pending.all?[]:state[pending.kind].filter(x=>x.id!==pending.id)};els.wallForm.reset();els.openingForm.reset();if(!persist())notify(label);render();}const fallback=$('#wall-width');(focusBack?.isConnected?focusBack:fallback).focus();pending=focusBack=null;});
render();if(loadError)notify(loadError,true);
