import { isValidEntries, loadEntries, saveEntries } from './storage.js';
import { createEntry, getSummary, removeEntry, updateStatus } from './state.js';
import { renderEntries, renderSummary } from './ui.js';

const form = document.querySelector('#entry-form'), entriesNode = document.querySelector('#entries'), filter = document.querySelector('#filter'), errorNode = document.querySelector('#form-error'), dialog = document.querySelector('#delete-dialog'), toast = document.querySelector('#toast'), exportButton = document.querySelector('#export-data'), importInput = document.querySelector('#import-data');
let { entries, error } = loadEntries(), pendingDeleteId = null, toastTimer;
document.querySelector('#today').textContent = new Intl.DateTimeFormat(undefined, { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date());
document.querySelector('#startedAt').valueAsDate = new Date();
function notify(message, persistent = false) { toast.textContent = message; toast.classList.add('show'); clearTimeout(toastTimer); if (!persistent) toastTimer = setTimeout(() => toast.classList.remove('show'), 5200); }
function commit(nextEntries) { const result = saveEntries(nextEntries); if (result.error) { notify(result.error, true); errorNode.textContent = result.error; errorNode.hidden = false; return false; } entries = nextEntries; return true; }
function render() { renderSummary(getSummary(entries)); document.querySelector('#total-count').textContent = String(entries.length); entriesNode.innerHTML = renderEntries(entries, filter.value); entriesNode.setAttribute('aria-busy', 'false'); }
if (error) notify(error, true); render();
form.addEventListener('submit', (event) => { event.preventDefault(); errorNode.hidden = true; const result = createEntry(new FormData(form)); if (result.error) { errorNode.textContent = result.error; errorNode.hidden = false; return; } if (!commit([result.entry, ...entries])) return; render(); form.reset(); document.querySelector('#startedAt').valueAsDate = new Date(); document.querySelector('#name').focus(); notify(`${result.entry.name} added to the bench.`); });
filter.addEventListener('change', render);
entriesNode.addEventListener('change', (event) => { const select = event.target.closest('[data-action="status"]'); if (!select) return; const id = select.closest('.entry').dataset.id; if (!commit(updateStatus(entries, id, select.value))) { render(); return; } render(); notify('Progress updated.'); });
entriesNode.addEventListener('click', (event) => { const button = event.target.closest('[data-action="delete"]'); if (!button) return; pendingDeleteId = button.closest('.entry').dataset.id; const entry = entries.find((item) => item.id === pendingDeleteId); document.querySelector('#delete-description').textContent = `Remove ${entry.name} from your bench? This can’t be undone.`; dialog.showModal(); });
dialog.addEventListener('close', () => { if (dialog.returnValue === 'confirm' && pendingDeleteId) { if (commit(removeEntry(entries, pendingDeleteId))) { render(); notify('Record removed.'); } } pendingDeleteId = null; });
exportButton.addEventListener('click', () => { const backup = new Blob([JSON.stringify(entries, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(backup); link.download = `rooted-backup-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(link.href); notify(`${entries.length} records exported.`); });
importInput.addEventListener('change', async () => { const file = importInput.files?.[0]; if (!file) return; try { const imported = JSON.parse(await file.text()); if (!isValidEntries(imported)) throw Error('invalid backup'); if (!confirm(`Replace your current ${entries.length} records with ${imported.length} imported records?`)) return; if (!commit(imported)) return; render(); notify(`${entries.length} records imported.`); } catch { notify('That file is not a valid Rooted backup.', true); } finally { importInput.value = ''; } });
