import { STATUSES, STATUS_LABELS } from './types.js';
import { escapeHtml } from './utils.js';
const formatter = new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
/** @param {string} date */
function formatDate(date) { return formatter.format(new Date(`${date}T12:00:00`)); }
/** @param {string} startedAt @param {Date} [today] */
export function startedLabel(startedAt, today = new Date()) { const start = new Date(`${startedAt}T12:00:00`); const current = new Date(today); current.setHours(12, 0, 0, 0); const days = Math.round((current - start) / 86400000); if (days === 0) return 'Started today'; if (days === 1) return 'Started 1 day ago'; if (days > 1) return `Started ${days} days ago`; return `Starts in ${Math.abs(days)} day${days === -1 ? '' : 's'}`; }
/** @param {import('./types.js').Propagation[]} entries @param {string} filter @param {string} [query=''] @param {string} [sort='newest'] */
export function renderEntries(entries, filter, query = '', sort = 'newest') {
  const normalizedQuery = query.trim().toLocaleLowerCase();
  const visible = (filter === 'all' ? entries : entries.filter((entry) => entry.status === filter)).filter((entry) => entry.name.toLocaleLowerCase().includes(normalizedQuery)).slice().sort((a, b) => sort === 'oldest' ? a.startedAt.localeCompare(b.startedAt) : sort === 'name' ? a.name.localeCompare(b.name) : sort === 'status' ? STATUSES.indexOf(a.status) - STATUSES.indexOf(b.status) : b.startedAt.localeCompare(a.startedAt));
  if (!visible.length) { const searching = normalizedQuery.length > 0; return `<div class="empty"><span>⌁</span><h3>${!entries.length ? 'Your bench is ready.' : searching ? 'No plants match your search.' : 'Nothing at this stage yet.'}</h3><p>${!entries.length ? 'Add the first little start you want to remember.' : searching ? 'Try a different plant name, or clear your filters.' : 'Try another stage, or add a fresh cutting.'}</p></div>`; }
  return visible.map((entry) => `<article class="entry" data-id="${entry.id}"><div class="entry-top"><span class="badge badge-${entry.status}">${STATUS_LABELS[entry.status]}</span><div class="entry-actions"><button class="text-button" data-action="edit" aria-label="Edit ${escapeHtml(entry.name)}">Edit</button><button class="icon-button delete" data-action="delete" aria-label="Remove ${escapeHtml(entry.name)}">×</button></div></div><h3>${escapeHtml(entry.name)}</h3><p class="method">${escapeHtml(entry.method)}</p><dl><div><dt>Started</dt><dd>${formatDate(entry.startedAt)}</dd></div></dl><p class="age">${startedLabel(entry.startedAt)}</p>${entry.note ? `<p class="note">${escapeHtml(entry.note)}</p>` : ''}<label class="status-control"><span>Progress</span><select data-action="status" aria-label="Update status for ${escapeHtml(entry.name)}">${Object.entries(STATUS_LABELS).map(([key, label]) => `<option value="${key}" ${key === entry.status ? 'selected' : ''}>${label}</option>`).join('')}</select></label></article>`).join('');
}
/** @param {ReturnType<import('./state.js').getSummary>} summary */
export function renderSummary(summary) { document.querySelector('#count-attempting').textContent = String(summary.attempting); document.querySelector('#count-rooting').textContent = String(summary.rooting); document.querySelector('#count-potted').textContent = String(summary.potted); document.querySelector('#count-failed').textContent = String(summary.failed); }
