from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    page = browser.new_page(viewport={"width": 1280, "height": 800})
    errors = []
    page.on("pageerror", lambda error: errors.append(str(error)))
    page.goto("http://127.0.0.1:4173", wait_until="networkidle")
    page.evaluate("localStorage.clear()")
    page.reload(wait_until="networkidle")
    page.locator("#plant-name").fill("Monstera")
    page.locator("#nickname").fill("Moss")
    page.locator("#frequency").fill("4")
    page.locator("#note").fill("Rotate toward the window")
    page.get_by_role("button", name="Add to collection").click()
    assert page.get_by_role("heading", name="Monstera").is_visible()
    plant_text = page.locator("#plant-list").inner_text()
    assert "due in" in plant_text.lower()
    page.get_by_role("button", name="Edit").click()
    assert page.locator("#last-watered").input_value()
    page.locator("#frequency").fill("5")
    page.get_by_role("button", name="Save changes").click()
    assert "Every 5 days" in page.locator("#plant-list").inner_text()
    page.get_by_role("button", name="Water now").click()
    assert "Next up:" in page.locator("#notices").inner_text()
    page.reload(wait_until="networkidle")
    assert page.get_by_role("heading", name="Monstera").is_visible()
    page.get_by_role("button", name="Remove Monstera").click()
    page.get_by_role("button", name="Remove plant").click()
    page.get_by_text("Your shelf is waiting.").wait_for()
    assert "Your shelf is waiting" in page.locator("#plant-list").inner_text()
    page.set_viewport_size({"width": 390, "height": 844})
    assert page.get_by_role("button", name="Night view").is_visible()
    assert not errors, errors
    browser.close()
