import{calculateEstimate,WAXES}from'./calculator.js';import{MAX_CANDLES,getBrowserStorage,readCandles,writeCandles}from'./storage.js';import{renderSavedCandles,setHidden,setText}from'./ui.js';
const state={estimate:null,entries:[],pending:'',focus:null,timer:0,touched:false},d={};
function el(id){const n=document.getElementById(id);if(!n)throw Error(`Missing ${id}`);return n}function init(){'estimatorForm weight unit wicks formMessage resultPanel rangeText exactText burnMeterFill summaryWeight summaryRate summaryWicks calculationStatus saveForm candleName saveMessage savedList emptyState collectionCount collectionMessage toast toastText toastClose deleteDialog deleteName appFallback'.split(' ').forEach(function map(id){d[id]=el(id)});bind();load();update()}
function bind(){d.estimatorForm.addEventListener('submit',submit);[d.weight,d.unit,d.wicks].forEach(function field(n){n.addEventListener('input',update);n.addEventListener('change',update)});document.querySelectorAll('input[name="wax"]').forEach(function wax(n){n.addEventListener('change',update)});d.saveForm.addEventListener('submit',save);d.toastClose.addEventListener('click',closeToast);d.deleteDialog.addEventListener('close',finishDelete)}
function read(){const wax=document.querySelector('input[name="wax"]:checked');return{weight:d.weight.value,unit:d.unit.value,wax:wax?.value||'',wicks:d.wicks.value}}
function submit(e){e.preventDefault();state.touched=true;update()}function update(){if([d.weight,d.unit,d.wicks].includes(document.activeElement)||document.activeElement?.name==='wax')state.touched=true;const r=calculateEstimate(read());setText(d.formMessage,'');if(!r.ok){state.estimate=null;invalid(r.errors)}else{state.estimate=r.value;render(r.value)}}
function invalid(errors){const message=state.touched?(errors.weight||errors.wicks||errors.unit||errors.wax||''):'';setText(d.rangeText,'Add a weight to see the range.');setText(d.exactText,message||'Your estimate will land here in hours and minutes.');['summaryWeight','summaryRate','summaryWicks'].forEach(function clear(id){setText(d[id],'—')});d.burnMeterFill.style.width='0';setText(d.calculationStatus,message?'Waiting for a complete estimate':'Live estimate');d.calculationStatus.classList.remove('is-calculating');setHidden(d.saveForm,true);if(message){setText(d.formMessage,message);d.weight.toggleAttribute('aria-invalid',Boolean(errors.weight));d.wicks.toggleAttribute('aria-invalid',Boolean(errors.wicks))}}
/** @param {CandleEstimate} e */
function render(e){setText(d.rangeText,e.rangeText);setText(d.exactText,`Exact average: ${e.durationText} of burn time`);setText(d.summaryWeight,`${fmt(e.ounces)} oz`);setText(d.summaryRate,`${WAXES[e.wax].rate} hr / oz`);setText(d.summaryWicks,String(e.wicks));d.burnMeterFill.style.width=`${Math.min(100,Math.max(8,e.hours/24*100))}%`;setText(d.calculationStatus,'Calculating…');d.calculationStatus.classList.add('is-calculating');setHidden(d.saveForm,false);window.requestAnimationFrame(function done(){d.calculationStatus.classList.remove('is-calculating');setText(d.calculationStatus,'Live estimate')});if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches){d.resultPanel.classList.remove('is-updated');window.requestAnimationFrame(function pulse(){d.resultPanel.classList.add('is-updated')})}}
function fmt(n){return new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(n)}
function save(e){e.preventDefault();setText(d.saveMessage,'');if(!state.estimate){setText(d.saveMessage,'Add a complete estimate first.');return}const name=d.candleName.value.trim();if(!name||name.length>36){setText(d.saveMessage,'Give this candle a name, up to 36 characters.');d.candleName.focus();return}if(state.entries.length>=MAX_CANDLES){setText(d.saveMessage,'Your shelf is full. Delete one first.');toast('Shelf full. Delete a candle to make room.','error',true);return}const x=state.estimate,entry={id:makeId(),name,result:x.rangeText,detail:`${fmt(x.ounces)} oz · ${WAXES[x.wax].label} · ${x.wicks} wick${x.wicks===1?'':'s'}`},next=[entry,...state.entries];if(!writeCandles(next,getBrowserStorage()).ok){setText(d.saveMessage,'Local saving is blocked; this estimate still works.');toast('Could not save locally.','error',true);return}state.entries=next;collection();d.candleName.value='';setText(d.saveMessage,'Saved to your shelf.');toast(`${name} joined your shelf.`)}
function load(){const r=readCandles(getBrowserStorage());state.entries=r.entries;collection();if(r.issue==='recovered'){setText(d.collectionMessage,'A damaged saved list was reset.');toast('A damaged saved list was reset.','error',true)}if(r.issue==='unavailable'){setText(d.collectionMessage,'Local saving is unavailable here.');toast('Saved candles are unavailable here.','error',true)}}function collection(){renderSavedCandles(d.savedList,d.emptyState,state.entries,askDelete);setText(d.collectionCount,`${state.entries.length} / ${MAX_CANDLES} saved`)}
function askDelete(id,button){state.pending=id;state.focus=button;const e=state.entries.find(function find(x){return x.id===id});setText(d.deleteName,e?.name||'this candle');if(d.deleteDialog.showModal)d.deleteDialog.showModal();else if(confirm(`Delete ${e?.name||'this candle'}?`))deleteCandle()}function finishDelete(){if(d.deleteDialog.returnValue==='delete')deleteCandle();else focusBack()}
function deleteCandle(){const next=state.entries.filter(function keep(e){return e.id!==state.pending});if(!writeCandles(next,getBrowserStorage()).ok){setText(d.collectionMessage,'Could not update the saved shelf.');toast('Could not update your saved shelf.','error',true);focusBack();return}state.entries=next;collection();setText(d.collectionMessage,'Candle removed from your shelf.');toast('Candle removed from your shelf.');focusBack();state.pending=''}function focusBack(){if(state.focus&&document.body.contains(state.focus))state.focus.focus();state.focus=null}
function toast(message,tone='success',persistent=false){clearTimeout(state.timer);setText(d.toastText,message);d.toast.dataset.tone=tone;setHidden(d.toastClose,!persistent);setHidden(d.toast,false);if(!persistent)state.timer=setTimeout(closeToast,5200)}function closeToast(){setHidden(d.toast,true);clearTimeout(state.timer)}function makeId(){return crypto?.randomUUID?.()||`candle-${Date.now()}-${Math.random().toString(36).slice(2)}`}
document.querySelectorAll('.input-panel,.result-panel').forEach(n=>n.style.color='var(--i)');try{init()}catch{const fallback=document.getElementById('appFallback');if(fallback)fallback.hidden=false}
