import { formatDistance } from './calculator.js';
/** @param {Document} doc */
export function createUI(doc) {
  const $ = (id) => /** @type {HTMLElement} */ (doc.getElementById(id));
  return {
    /** @param {import('./calculator.js').Trip} trip */ setInputs(trip) { ['distance','efficiency','tank','price','start'].forEach(k => { /** @type {HTMLInputElement} */($(k)).value = String(trip[k]); }); /** @type {HTMLSelectElement} */($('currency')).value=trip.currency; this.setUnit(trip.unit,trip.currency); },
    /** @param {'imperial'|'metric'} unit @param {import('./calculator.js').Currency} currency */ setUnit(unit,currency) { doc.querySelectorAll('[data-unit]').forEach(b => /** @type {HTMLButtonElement} */(b).setAttribute('aria-pressed', String(/** @type {HTMLButtonElement} */(b).dataset.unit === unit))); $('distance-unit').textContent=unit==='imperial'?'miles':'km'; $('efficiency-unit').textContent=unit==='imperial'?'mpg':'L/100km'; $('tank-unit').textContent=unit==='imperial'?'gallons':'liters'; $('price-unit').textContent=`${currency} / ${unit==='imperial'?'gallon':'liter'}`; },
    /** @param {import('./calculator.js').Trip} trip @param {import('./calculator.js').Plan|null} plan @param {string|null} error */ render(trip, plan, error) { $('start-output').textContent=`${trip.start}%`; $('form-message').textContent=error||''; if(!plan){ $('stops').textContent='—';$('cost').textContent='—';$('range').textContent='—';$('fuel-required-value').textContent='—';$('stops-detail').textContent='Complete every field';$('fuel-detail').textContent='Enter valid trip details';$('range-detail').textContent='Based on your 10% reserve';$('plan-status').textContent='Needs details';return; } const money=new Intl.NumberFormat(undefined,{style:'currency',currency:trip.currency,maximumFractionDigits:trip.currency==='IDR'?0:2}).format(plan.cost); $('stops').textContent=String(plan.stops); $('stops-detail').textContent=plan.stops===1?'one stop planned':'stops planned'; $('cost').textContent=money; $('fuel-detail').textContent=`${plan.fuel.toFixed(1)} ${trip.unit==='imperial'?'gal':'L'} used`; $('fuel-required-value').textContent=`${plan.fuel.toFixed(1)} ${trip.unit==='imperial'?'gal':'L'}`; $('range').textContent=formatDistance(plan.range,trip.unit); $('range-detail').textContent=`${formatDistance(Math.max(0,plan.range-(plan.range*.05)),trip.unit)} comfortable range`; $('plan-status').textContent='Live'; },
    /** @param {string|null} message */ setSaveMessage(message){$('save-message').textContent=message||'';},
    /** @param {string} message @param {boolean} error */ toast(message,error=false){const el=$('toast');el.textContent=message;el.className=`toast${error?' error':''}`;el.hidden=false;clearTimeout(this.timer);this.timer=setTimeout(()=>el.hidden=true,5000);}, timer:0
  };
}
